include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_build_context_synchronously: true
    always_declare_return_types: true
    avoid_print: true
    prefer_final_locals: true
    unnecessary_this: true
    annotate_overrides: true
    prefer_typing_uninitialized_variables: true
    avoid_void_async: true
    recursive_getters: true
    use_rethrow_when_possible: true
