arb-dir: lib/app/localization/
template-arb-file: en.arb
output-localization-file: localization_key.dart
output-dir: lib/generated
untranslated-messages-file: untranslated_messages.json


translator:
  targets:
    - en