# file: .github/workflows/main.yml

name: 'Build & Release dig_cli'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Trigger on tags like v1.0.0, v1.2.3 etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      # STEP 1: Compile for Linux
      - name: 'Build for Linux'
        run: |
          dart pub get
          dart compile exe bin/dig_cli.dart -o dig-linux

      # STEP 2: Compile for Windows
      - name: 'Build for Windows'
        run: |
          dart pub get
          dart compile exe bin/dig_cli.dart -o dig-windows.exe

      # STEP 3: Compile for macOS
      - name: 'Build for macOS'
        run: |
          dart pub get
          dart compile exe bin/dig_cli.dart -o dig-macos

      # STEP 4: Create the GitHub Release and Upload Binaries
      - name: 'Create GitHub Release'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dig-linux
            dig-windows.exe
            dig-macos
          body: |
            Official release for version ${{ github.ref_name }}.
            Download the executable for your platform below.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}