# file: .github/workflows/validate.yml

name: 'Validate Code'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  # Job 1: Check formatting
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: 'Check formatting'
        run: dart format --output=none --set-exit-if-changed .

  # Job 2: Run analysis and tests
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: 'Install dependencies'
        run: dart pub get

      - name: 'Analyze project source'
        run: dart analyze --fatal-infos --fatal-warnings

      # - name: 'Run tests'
      #   run: dart test